// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.iceproxy.v1.common;

public interface _ProxyOperations
{
    String getSalt(String userName, Ice.Current __current);

    LoginResult login(LoginInfo loginInfo, ClientCallback client, Ice.Current __current);

    int httpGet(String url, Ice.Current __current);
}
