// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.iceproxy.v1.common;

public interface ClientCallbackPrx extends Ice.ObjectPrx
{
    public int httpGetResult(HttpResponse resp);

    public int httpGetResult(HttpResponse resp, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_httpGetResult(HttpResponse resp);

    public Ice.AsyncResult begin_httpGetResult(HttpResponse resp, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_httpGetResult(HttpResponse resp, Ice.Callback __cb);

    public Ice.AsyncResult begin_httpGetResult(HttpResponse resp, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_httpGetResult(HttpResponse resp, Callback_ClientCallback_httpGetResult __cb);

    public Ice.AsyncResult begin_httpGetResult(HttpResponse resp, java.util.Map<String, String> __ctx, Callback_ClientCallback_httpGetResult __cb);

    public Ice.AsyncResult begin_httpGetResult(HttpResponse resp, 
                                               IceInternal.Functional_IntCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_httpGetResult(HttpResponse resp, 
                                               IceInternal.Functional_IntCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_httpGetResult(HttpResponse resp, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_IntCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_httpGetResult(HttpResponse resp, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_IntCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public int end_httpGetResult(Ice.AsyncResult __result);
}
