// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.iceproxy.v1.common;

public class LoginInfo implements java.lang.Cloneable, java.io.Serializable
{
    public String userName;

    public String salt;

    public String passwordAndSalt;

    public LoginInfo()
    {
        userName = "";
        salt = "";
        passwordAndSalt = "";
    }

    public LoginInfo(String userName, String salt, String passwordAndSalt)
    {
        this.userName = userName;
        this.salt = salt;
        this.passwordAndSalt = passwordAndSalt;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        LoginInfo _r = null;
        if(rhs instanceof LoginInfo)
        {
            _r = (LoginInfo)rhs;
        }

        if(_r != null)
        {
            if(userName != _r.userName)
            {
                if(userName == null || _r.userName == null || !userName.equals(_r.userName))
                {
                    return false;
                }
            }
            if(salt != _r.salt)
            {
                if(salt == null || _r.salt == null || !salt.equals(_r.salt))
                {
                    return false;
                }
            }
            if(passwordAndSalt != _r.passwordAndSalt)
            {
                if(passwordAndSalt == null || _r.passwordAndSalt == null || !passwordAndSalt.equals(_r.passwordAndSalt))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::common::LoginInfo");
        __h = IceInternal.HashUtil.hashAdd(__h, userName);
        __h = IceInternal.HashUtil.hashAdd(__h, salt);
        __h = IceInternal.HashUtil.hashAdd(__h, passwordAndSalt);
        return __h;
    }

    public LoginInfo
    clone()
    {
        LoginInfo c = null;
        try
        {
            c = (LoginInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(userName);
        __os.writeString(salt);
        __os.writeString(passwordAndSalt);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        userName = __is.readString();
        salt = __is.readString();
        passwordAndSalt = __is.readString();
    }

    static public void
    __write(IceInternal.BasicStream __os, LoginInfo __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public LoginInfo
    __read(IceInternal.BasicStream __is, LoginInfo __v)
    {
        if(__v == null)
        {
             __v = new LoginInfo();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final LoginInfo __nullMarshalValue = new LoginInfo();

    public static final long serialVersionUID = 1272875406L;
}
