// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.iceproxy.v1.common;

public interface ProxyPrx extends Ice.ObjectPrx
{
    public String getSalt(String userName);

    public String getSalt(String userName, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getSalt(String userName);

    public Ice.AsyncResult begin_getSalt(String userName, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getSalt(String userName, Ice.Callback __cb);

    public Ice.AsyncResult begin_getSalt(String userName, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getSalt(String userName, Callback_Proxy_getSalt __cb);

    public Ice.AsyncResult begin_getSalt(String userName, java.util.Map<String, String> __ctx, Callback_Proxy_getSalt __cb);

    public Ice.AsyncResult begin_getSalt(String userName, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getSalt(String userName, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getSalt(String userName, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getSalt(String userName, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public String end_getSalt(Ice.AsyncResult __result);

    public LoginResult login(LoginInfo loginInfo, ClientCallback client);

    public LoginResult login(LoginInfo loginInfo, ClientCallback client, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(LoginInfo loginInfo, ClientCallback client);

    public Ice.AsyncResult begin_login(LoginInfo loginInfo, ClientCallback client, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(LoginInfo loginInfo, ClientCallback client, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(LoginInfo loginInfo, ClientCallback client, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(LoginInfo loginInfo, ClientCallback client, Callback_Proxy_login __cb);

    public Ice.AsyncResult begin_login(LoginInfo loginInfo, ClientCallback client, java.util.Map<String, String> __ctx, Callback_Proxy_login __cb);

    public Ice.AsyncResult begin_login(LoginInfo loginInfo, 
                                       ClientCallback client, 
                                       IceInternal.Functional_GenericCallback1<LoginResult> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_login(LoginInfo loginInfo, 
                                       ClientCallback client, 
                                       IceInternal.Functional_GenericCallback1<LoginResult> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_login(LoginInfo loginInfo, 
                                       ClientCallback client, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<LoginResult> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_login(LoginInfo loginInfo, 
                                       ClientCallback client, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<LoginResult> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public LoginResult end_login(Ice.AsyncResult __result);

    public int httpGet(String url);

    public int httpGet(String url, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_httpGet(String url);

    public Ice.AsyncResult begin_httpGet(String url, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_httpGet(String url, Ice.Callback __cb);

    public Ice.AsyncResult begin_httpGet(String url, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_httpGet(String url, Callback_Proxy_httpGet __cb);

    public Ice.AsyncResult begin_httpGet(String url, java.util.Map<String, String> __ctx, Callback_Proxy_httpGet __cb);

    public Ice.AsyncResult begin_httpGet(String url, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_httpGet(String url, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_httpGet(String url, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_httpGet(String url, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_IntCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public int end_httpGet(Ice.AsyncResult __result);
}
