// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.iceproxy.v1.common;

public interface Proxy extends Ice.Object,
                               _ProxyOperations, _ProxyOperationsNC
{
    public static final String ice_staticId = "::common::Proxy";

    public static final long serialVersionUID = 1509504956L;
}
